std_msgs/Header header
CAN_GWAY1 GWAY1
CAN_GWAY2 GWAY2
CAN_GWAY3 GWAY3
CAN_GWAY4 GWAY4
# CAN_GWAY5 GWAY5
# CAN_GWAY10 GWAY10

## GWAY1
#float64 Wheel_Velocity_FR
#float64 Wheel_Velocity_RL
#float64 Wheel_Velocity_RR
#float64 Wheel_Velocity_FL
## GWAY2
#float64 Lateral_Accel_Speed
#float64 Parking_Brake_Active
#float64 AirConditioner_On
#float64 Steering_Angle
#float64 Steering_Speed
#float64 Steering_Tq
## GWAY3
#float64 Accel_Pedal_Position
#float64 Brake_Active
#float64 BrakeMasterCylinder_Pressure
#float64 Engine_Speed
#float64 Gear_Target_Change
#float64 GearSelDisp
#float64 Throttle_Position
## float64 ACC_ACT_Status
## GWAY4
#float64 Cluster_Odometer
#float64 Longitudinal_Accel_Speed
#float64 Vehicle_Speed_Engine
#float64 Yaw_Rate_Sensor
